! Unit test for the Verlet integration scheme, verifying that position updates follow the kinematic equation r = r0 + v0*t + 0.5*a*t^2.
! NOTE: Structured and partially generated by ChatGPT !!

program test_verlet
  use verlet_al
  ! We need auxiliary modules to initialize variables if required by your makefile dependencies
  use treat_output 
  implicit none

  ! Parameters and Variables (Renamed for consistency)
  integer, parameter :: Natoms = 1
  double precision :: coord(Natoms,3), velocity(Natoms,3), acc(Natoms,3), mass(Natoms)
  double precision :: dt = 1.0d0, epsilon = 1.0d0, sigma = 1.0d0
  double precision :: E, V_p, T
  integer :: u_out = 10, u_xyz = 20, iter = 1, M = 1
  
  write(*,*) "=== TEST MODULE: VERLET ALGORITHM ==="

  ! Prepare dummy files so verlet can write output without crashing
  open(u_out, file='dummy_verlet.out')
  open(u_xyz, file='dummy_verlet.xyz')

  ! Initialization: Atom at rest, but with initial acceleration
  coord = 0.0d0
  velocity   = 0.0d0
  mass  = 1.0d0
  
  ! Setup: Acceleration in X = 2.0
  acc = 0.0d0
  acc(1,1) = 2.0d0 

  ! Call Verlet for 1 step
  ! Note: Verlet calculates new forces and positions internally.
  ! For a single atom, internal force will be 0 (compute_acc returns 0).
  ! But Verlet uses the *current* acceleration (acc) to move position first.
  ! eq: r(t+dt) = r(t) + v*dt + 0.5*a*dt^2
  ! r_new = 0 + 0 + 0.5 * 2.0 * 1.0^2 = 1.0
  
  call verlet_algorithm(Natoms, coord, velocity, acc, dt, epsilon, sigma, mass, T, V_p, E, u_xyz, u_out, iter, M)

  ! --- TEST 1: Position Update ---
  write(*,*) "Initial Pos X: 0.0"
  write(*,*) "Initial Acc X: 2.0"
  write(*,*) "Time step    : 1.0"
  write(*,*) "Final Pos X  :", coord(1,1)

  if (abs(coord(1,1) - 1.0d0) < 1e-6) then
     write(*,*) "[OK] Verlet: Position updated correctly according to a*dt^2/2."
  else
     write(*,*) "[FAIL] Verlet: Incorrect position. Value:", coord(1,1), "Expected: 1.0"
  end if

  ! Cleanup: Close and delete dummy files
  close(u_out, status='delete')
  close(u_xyz, status='delete')

end program test_verlet
